language: java
sudo: false

dist: trusty

jdk:
- oraclejdk8

before_install:

install:
- mvn clean install -DskipTests -B -V
- mvn test

script:
- sh ./check_format.sh
- mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)